INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10000, 'Acitretin','Ranbaxy','Capsule', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10001, 'Adefovir','Ranbaxy','Capsule', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10002, 'Alitretinoin*','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10003, 'Alogliptin*','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10004, 'Amorolfine HCl','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10005, 'Apixaban*','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10006, 'Asenapine Maleate','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10007, 'Atazanavir','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10008, 'Atorvastatin Calcium','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10009, 'Axitnib*','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10010, 'Azilsartan medoxomil potassium','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10011, 'Benazepril HCl','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10012, 'Biapenem','Ranbaxy','Tablet', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10013, 'Boceprevir*','Ranbaxy','Capsule', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10014, 'Bosentan','Ranbaxy','Capsule', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10015, 'Candesartan cilexetil','Ranbaxy','Lotion', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10016, 'Cefaclor','Ranbaxy','Lotion', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10017, 'Cefdinir','Ranbaxy','Lotion', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10018, 'Cefozopran*','Ranbaxy','Lotion', 20);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10019, 'Cefpodoxime proxetil','Ranbaxy','Lotion', 32);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10020, 'Cefprozil','Ranbaxy','Lotion', 32);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10021, 'Ceftaroline fosamil*','Ranbaxy','Other', 32);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10022, 'Cefuroxime axetil','Ranbaxy','Other', 32);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10023, 'Cilazapril','Cipla','Other', 32);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10024, 'Cinacalcet','Cipla','Other', 45);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10025, 'Ciprofloxacin base','Cipla','Capsule', 46);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10026, 'Ciprofloxacin HCl','Cipla','Capsule', 47);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10027, 'Clarithromycin','Cipla','Capsule', 48);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10028, 'Clarithromycin Granules 27.5%','Cipla','Lotion', 49);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10029, 'Clarithromycin Granules 43.75%','Cipla','Lotion', 50);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10030, 'Clorazepate di potassium','Cipla','Lotion', 51);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10031, 'Dabigatran etexilate','Cipla','Lotion', 52);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10032, 'Darunavir*','Cipla','Lotion', 53);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10033, 'Dasatinib*','Cipla','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10034, 'Deferasirox','Cipla','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10035, 'Desloratadine','Cipla','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10036, 'Dexlansoprazole','Cipla','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10037, 'Donepezil HCl','Cipla','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10038, 'Doripenem','Glaxo','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10039, 'Doxycycline HCl','Glaxo','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10040, 'Doxycycline monohydrate','Glaxo','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10041, 'Dronedarone*','Glaxo','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10042, 'Eletriptan','Glaxo','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10043, 'Entecavir','Glaxo','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10044, 'Erlotinib','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10045, 'Ertapenem*','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10046, 'Eslicarbazepine Acetate','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10047, 'Esomeprazole Mg','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10048, 'Faropenem sodium','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10049, 'Febuxostat','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10050, 'Fesoterodine*','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10051, 'Fexofenadine HCl','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10052, 'Fluvastatin sodium','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10053, 'Fondaparinux*','Glaxo','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10054, 'Fosinopril sodium','Lupin','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10055, 'Gabapentin','Lupin','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10056, 'Imatinib','Lupin','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10057, 'Imipenem + Cilastatin Sodium sterile blend','Lupin','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10058, 'Imipenem / Cilastatin','Lupin','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10059, 'Irbesartan','Lupin','Lotion', 21);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10060, 'Isotretinoin','Lupin','Lotion', 22);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10061, 'Lacosamide','Lupin','Other', 23);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10062, 'Lansoprazole','Lupin','Other', 24);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10063, 'Lenalidomide','Lupin','Other', 25);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10064, 'Levofloxacin','Lupin','Other', 26);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10065, 'Linagliptin','Lupin','Tablet', 27);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10066, 'Lopinavir','Lupin','Tablet', 28);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10067, 'Lorazepam','Lupin','Tablet', 29);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10068, 'Lurasidone','Lupin','Tablet', 30);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10069, 'Memantine','Dr Reddys','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10070, 'Meropenem','Dr Reddys','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10071, 'Midazolam base','Dr Reddys','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10072, 'Milnacipran HCl','Dr Reddys','Tablet', 33);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10073, 'Nevirapine','Dr Reddys','Tablet', 34);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10074, 'Nilotinib*','Dr Reddys','Tablet', 35);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10075, 'Ofloxacin','Dr Reddys','Other', 36);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10076, 'Olanzapine','Dr Reddys','Other', 37);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10077, 'Olmesartan','Dr Reddys','Other', 38);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10078, 'Orlistat','Dr Reddys','Other', 39);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10079, 'Orlistat Pellets 50%','Dr Reddys','Lotion', 40);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10080, 'Palonosetron','Dr Reddys','Lotion', 41);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10081, 'Pazopanib*','Dr Reddys','Lotion', 42);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10082, 'Pentazocine','Dr Reddys','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10083, 'Rabeprazole sodium','Dr Reddys','Lotion', 44);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10084, 'Repaglinide','Dr Reddys','Lotion', 45);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10085, 'Rilpivirine*','Dr Reddys','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10086, 'Ritonavir','Dr Reddys','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10087, 'Rivaroxaban*','Dr Reddys','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10088, 'Roflumilast*','Dr Reddys','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10089, 'Rosuvastatin Calcium','Torrent Pharmaceuticals Ltd','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10090, 'Ruxolitinib*','Torrent Pharmaceuticals Ltd','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10091, 'Saxagliptin*','Torrent Pharmaceuticals Ltd','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10092, 'Sertraline HCl','Torrent Pharmaceuticals Ltd','Capsule', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10093, 'Simvastatin','Torrent Pharmaceuticals Ltd','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10094, 'Sitagliptin','Torrent Pharmaceuticals Ltd','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10095, 'Solifenacin succinate','Torrent Pharmaceuticals Ltd','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10096, 'Sorafenib','Torrent Pharmaceuticals Ltd','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10097, 'Sunitinib*','Torrent Pharmaceuticals Ltd','Tablet', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10098, 'Tamsulosin HCl','Torrent Pharmaceuticals Ltd','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10099, 'Tamsulosin Pellets','Torrent Pharmaceuticals Ltd','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10100, 'Telaprevir*','Torrent Pharmaceuticals Ltd','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10101, 'Telmisartan','Torrent Pharmaceuticals Ltd','Lotion', 43);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10102, 'Ticagrelor*','Torrent Pharmaceuticals Ltd','Lotion', 0);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10103, 'Tigecycline','Torrent Pharmaceuticals Ltd','Lotion', 0);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10104, 'Tofacitinib*','Torrent Pharmaceuticals Ltd','Tablet', 0);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10105, 'Valacyclovir','Torrent Pharmaceuticals Ltd','Capsule', 0);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10106, 'Valgancyclovir','Torrent Pharmaceuticals Ltd','Capsule', 0);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10107, 'Valsartan','Torrent Pharmaceuticals Ltd','Capsule', 0);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10108, 'Vildagliptin','Torrent Pharmaceuticals Ltd','Capsule', 0);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10109, 'Voglibose','Torrent Pharmaceuticals Ltd','Capsule', 0);
INSERT INTO DRUGS(DRG_ID, DRG_NM, MFR, TYP, AVAIL_UNITS) VALUES (10110, 'Voriconazole','Torrent Pharmaceuticals Ltd','Capsule', 0);
