
-- CREATE DRUGS
DROP TABLE DRUGS;
CREATE TABLE DRUGS(
    DRG_ID  BIGINT PRIMARY KEY,
    DRG_NM  VARCHAR(50),
    MFR     VARCHAR(50),
    TYP     VARCHAR(10)
);

-- CREATE DRUG_BATCH
CREATE TABLE DRUG_BATCH (	
	DRUG_ID	BIGINT,
	BATCH_ID BIGINT PRIMARY KEY,
	UNIT_PP	NUMERIC(5,2),
	UNIT_RP	NUMERIC(5,2),
	AVAIL_UNITS INT,
	EXP_DT	TIMESTAMP
);


-- CREATE PARTY
DROP TABLE PARTY;
CREATE TABLE PARTY (
    PRTY_ID	BIGINT PRIMARY KEY,
    PRTY_NM	VARCHAR(100),
    PRTY_ADD	VARCHAR(200),
    CNTCT_NO	VARCHAR(15)
);

-- CREATE SALE TRANSACTION
DROP TABLE SALE_TRANSACTION;
CREATE TABLE SALE_TRANSACTION(
    TRNSCT_ID       BIGINT PRIMARY KEY,
    PATIENT_NM      VARCHAR(50),
    PATIENT_AGE     SMALLINT,
    SALE_DTLS_ID    BIGINT,
    DATE            TIMESTAMP,
    DOCTOR_NM       VARCHAR(50),
    TOT_AMT         NUMERIC(10,2)
);

--CREATE SALE DETAILS
DROP TABLE SALE_DTLS;
CREATE TABLE SALE_DTLS(
    ID              BIGINT PRIMARY KEY, 
    SALE_DTLS_ID    BIGINT,
    DRUG_ID         BIGINT,
    QTY             INT,
    UNIT_PRC        NUMERIC(5,2),
    BATCH_ID		BIGINT
);

--TRANSACTION OF PURCHASE
DROP TABLE PURCHASE_TRANSACTION;
CREATE TABLE PURCHASE_TRANSACTION( 
    TRNSCT_ID	BIGINT PRIMARY KEY,
    PRTY_ID	BIGINT,
    DATE	TIMESTAMP,
    DRUG_ID	BIGINT,
	QTY	INT,
    TOT_AMT	NUMERIC(10,2)
);